name: Snapcraft Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true

      - name: Build
        run: snapcraft build
